/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Not Found error
 */
export type ApiErrorNotFoundData = {
  status: number;
  error: string;
  code: string;
};

/**
 * Not Found error
 */
export class ApiErrorNotFound extends Error {
  status: number;
  error: string;
  code: string;

  /** The original data that was passed to this error instance. */
  data$: ApiErrorNotFoundData;

  constructor(err: ApiErrorNotFoundData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.status = err.status;
    this.error = err.error;
    this.code = err.code;

    this.name = "ApiErrorNotFound";
  }
}

/** @internal */
export const ApiErrorNotFound$inboundSchema: z.ZodType<
  ApiErrorNotFound,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number().int(),
  error: z.string(),
  code: z.string(),
})
  .transform((v) => {
    return new ApiErrorNotFound(v);
  });

/** @internal */
export type ApiErrorNotFound$Outbound = {
  status: number;
  error: string;
  code: string;
};

/** @internal */
export const ApiErrorNotFound$outboundSchema: z.ZodType<
  ApiErrorNotFound$Outbound,
  z.ZodTypeDef,
  ApiErrorNotFound
> = z.instanceof(ApiErrorNotFound)
  .transform(v => v.data$)
  .pipe(z.object({
    status: z.number().int(),
    error: z.string(),
    code: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ApiErrorNotFound$ {
  /** @deprecated use `ApiErrorNotFound$inboundSchema` instead. */
  export const inboundSchema = ApiErrorNotFound$inboundSchema;
  /** @deprecated use `ApiErrorNotFound$outboundSchema` instead. */
  export const outboundSchema = ApiErrorNotFound$outboundSchema;
  /** @deprecated use `ApiErrorNotFound$Outbound` instead. */
  export type Outbound = ApiErrorNotFound$Outbound;
}
