workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    petstore-oas:
        inputs:
            - location: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/test123/test123ws/petstore-oas
targets:
    petstore:
        target: typescript
        source: petstore-oas
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/test123/test123ws/petstore-oas-typescript-code-samples
            blocking: false
