/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteOrderRequest = {
  /**
   * ID of the order that needs to be deleted
   */
  orderId: number;
};

/** @internal */
export const DeleteOrderRequest$inboundSchema: z.ZodType<
  DeleteOrderRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  orderId: z.number().int(),
});

/** @internal */
export type DeleteOrderRequest$Outbound = {
  orderId: number;
};

/** @internal */
export const DeleteOrderRequest$outboundSchema: z.ZodType<
  DeleteOrderRequest$Outbound,
  z.ZodTypeDef,
  DeleteOrderRequest
> = z.object({
  orderId: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteOrderRequest$ {
  /** @deprecated use `DeleteOrderRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteOrderRequest$inboundSchema;
  /** @deprecated use `DeleteOrderRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteOrderRequest$outboundSchema;
  /** @deprecated use `DeleteOrderRequest$Outbound` instead. */
  export type Outbound = DeleteOrderRequest$Outbound;
}

export function deleteOrderRequestToJSON(
  deleteOrderRequest: DeleteOrderRequest,
): string {
  return JSON.stringify(
    DeleteOrderRequest$outboundSchema.parse(deleteOrderRequest),
  );
}

export function deleteOrderRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteOrderRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteOrderRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteOrderRequest' from JSON`,
  );
}
